// Login
export const FETCH_LOGOUT_TRIGGERED = 'FETCH_LOGOUT_TRIGGERED';
export const FETCH_LOGOUT_FAILED = 'FETCH_LOGOUT_FAILED';
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';

export const FETCH_LOGIN_START_TRIGGERED = 'FETCH_LOGIN_START_TRIGGERED';
export const FETCH_LOGIN_START_FAILED = 'FETCH_LOGIN_START_FAILED';
export const FETCH_LOGIN_START_SUCCESS = 'FETCH_LOGIN_START_SUCCESS';

export const FETCH_LOGIN_FINISH_TRIGGERED = 'FETCH_LOGIN_FINISH_TRIGGERED';
export const FETCH_LOGIN_FINISH_FAILED = 'FETCH_LOGIN_FINISH_FAILED';
export const FETCH_LOGIN_FINISH_SUCCESS = 'FETCH_LOGIN_FINISH_SUCCESS';